name: Build

# Controls when the action will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    # Tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build the robot code
      run: ./gradlew build
